### ISSUE TITLE
[bittrex] Getting rate bans

### ISSUE THREAD

**Issue by badgerwithagun** [gruelbox/orko#129]
```
Jan 09 15:07:06 oco-active app/web.1: ERROR [2019-01-09 15:07:05,843] com.gruelbox.orko.marketdata.MarketDataSubscriptionManager: Error fetching market data: bittrex/BTC/VTC/USER_TRADE_HISTORY 
Jan 09 15:07:06 oco-active app/web.1: ! org.knowm.xchange.exceptions.ExchangeException: Call to GetOrderHistory was throttled. Try again in 60 seconds. 
Jan 09 15:07:06 oco-active app/web.1: ! at org.knowm.xchange.bittrex.BittrexErrorAdapter.adapt(BittrexErrorAdapter.java:20) 
Jan 09 15:07:06 oco-active app/web.1: ! at org.knowm.xchange.bittrex.service.BittrexTradeService.getTradeHistory(BittrexTradeService.java:113) 
Jan 09 15:07:06 oco-active app/web.1: ! at com.gruelbox.orko.marketdata.MarketDataSubscriptionManager.pollAndEmitUserTradeHistory(MarketDataSubscriptionManager.java:682) 
Jan 09 15:07:06 oco-active app/web.1: ! at com.gruelbox.orko.marketdata.MarketDataSubscriptionManager.fetchAndBroadcast(MarketDataSubscriptionManager.java:661) 
Jan 09 15:07:06 oco-active app/web.1: ! at com.gruelbox.orko.marketdata.MarketDataSubscriptionManager.pollExchange(MarketDataSubscriptionManager.java:569) 
Jan 09 15:07:06 oco-active app/web.1: ! at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) 
Jan 09 15:07:06 oco-active app/web.1: ! at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) 
Jan 09 15:07:06 oco-active app/web.1: ! at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) 
Jan 09 15:07:06 oco-active app/web.1: ! at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) 
Jan 09 15:07:06 oco-active app/web.1: ! at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) 
Jan 09 15:07:06 oco-active app/web.1: ! at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) 
Jan 09 15:07:06 oco-active app/web.1: ! at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) 
Jan 09 15:07:06 oco-active app/web.1: ! at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) 
Jan 09 15:07:06 oco-active app/web.1: ! at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) 
```

**Comment by badgerwithagun** [comment]
Still getting rate bans even with rate dialled way back from the published maximums.

Dialled back again.
