### ISSUE TITLE
Copying price to stop price in trade panel causes "TypeError: n.order.merge is not a function"

### ISSUE THREAD

**Issue by badgerwithagun** [gruelbox/orko#148]
**To Reproduce**
1. Open the stop tab in the trade panel
1. Click in the stop price
1. Click a price in the order book
1. "Something went wrong"...

**Expected behavior**
Price is copied

**Screenshots**
![image](https://user-images.githubusercontent.com/6483013/51305269-4b912080-1a32-11e9-978c-ad9c6128109e.png)

**Comment by jakubkalicki** [comment]
Hey @badgerwithagun,
I was curious about this project, so i have downloaded latest release 0.14.3 and looked around. 
When playing with Simulator exchange, exactly this issue occurred. Not sure when exactly though, because now i can't reproduce it.

**Comment by badgerwithagun** [comment]
Hi @jakubkalicki - is it fixed in the latest snapshot? I've not done a release for a while.

**Comment by jakubkalicki** [comment]
Does it use Java 11?

**Comment by badgerwithagun** [comment]
Yes. I'm midway through a big tech update, which includes Java 11. You can use the docker image `gruelbox/orko` instead, if installing Java 11 is inconvenient.

**Comment by jakubkalicki** [comment]
I decided that i will fork the project and build it locally. However, testSubscriptionsDirect in AbstractMarketDataFullStackTest is currently failing. 

Could you help me with this one? 
Does it occur for you as well?

`
java.lang.AssertionError: Missing two responses (A) for simulated/USD/BTC/ORDERBOOK

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.gruelbox.orko.exchange.AbstractMarketDataFullStackTest.lambda$testSubscriptionsDirect$5(AbstractMarketDataFullStackTest.java:155)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base/java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:1957)
	at java.base/java.util.concurrent.ForkJoinTask.tryExternalHelp(ForkJoinTask.java:378)
	at java.base/java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:323)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:412)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at com.gruelbox.orko.exchange.AbstractMarketDataFullStackTest.testSubscriptionsDirect(AbstractMarketDataFullStackTest.java:151)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)`

**Comment by badgerwithagun** [comment]
Yeah I've seen this one intermittently. Been too busy working on other bits to do anything about it.
