### ISSUE TITLE
[bittrex] NPE when fetching balances

### ISSUE THREAD

**Issue by badgerwithagun** [gruelbox/orko#269]
```
ERROR [2019-02-28 01:14:18,549] com.gruelbox.orko.marketdata.MarketDataSubscriptionManager: Error fetching data for bittrex 
java.lang.NullPointerException: nulll
 ! at java.math.BigDecimal.subtract(BigDecimal.java:1438) 
 ! at org.knowm.xchange.bittrex.BittrexAdapters.adaptWallet(BittrexAdapters.java:236) ``

**Comment by badgerwithagun** [comment]
Fixed
