### ISSUE TITLE
[kraken] UndeclaredThrowableException in logs

### ISSUE THREAD

**Issue by badgerwithagun** [gruelbox/orko#272]
Looks like rescu is wrapping the `SocketTimeoutException`. Is `IOException` thrown by the proxied interface?

```
ERROR [2019-03-03 18:48:18,363] com.gruelbox.orko.marketdata.MarketDataSubscriptionManager: Error fetching data for kraken 
! java.net.SocketTimeoutException: Read timed out 
! at java.net.SocketInputStream.socketRead0(Native Method) 
! at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) 
! at java.net.SocketInputStream.read(SocketInputStream.java:171) 
! at java.net.SocketInputStream.read(SocketInputStream.java:141) 
! at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) 
! at sun.security.ssl.InputRecord.read(InputRecord.java:503) 
! at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) 
! at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933) 
! at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) 
! at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) 
! at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) 
! at java.io.BufferedInputStream.read(BufferedInputStream.java:345) 
! at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) 
! at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) 
! at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) 
! at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) 
! at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) 
! at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347) 
! at si.mazi.rescu.HttpTemplate.receive(HttpTemplate.java:122) 
! at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:162) 
! at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:119) 
! ... 14 common frames omitted 
! Causing: java.lang.reflect.UndeclaredThrowableException: null 
! at com.sun.proxy.$Proxy109.getTicker(Unknown Source) 
! at org.knowm.xchange.kraken.service.KrakenMarketDataServiceRaw.getKrakenTicker(KrakenMarketDataServiceRaw.java:48) 
! at org.knowm.xchange.kraken.service.KrakenMarketDataService.getTicker(KrakenMarketDataService.java:35) 
! at com.gruelbox.orko.marketdata.MarketDataSubscriptionManager$Poller.pollAndEmitTicker(MarketDataSubscriptionManager.java:949)
```

**Comment by badgerwithagun** [comment]
XChange issue
