### ISSUE TITLE
[bitmex] NPE fetching trades

### ISSUE THREAD

**Issue by badgerwithagun** [gruelbox/orko#311]
**Describe the bug**
In logs:
```
Error fetching data for bitmex 
 ! java.lang.NullPointerException: null 
 ! at org.knowm.xchange.bitmex.BitmexAdapters.adaptOrderType(BitmexAdapters.java:211) 
 ! at org.knowm.xchange.bitmex.BitmexAdapters.adaptTrade(BitmexAdapters.java:134) 
 ! at org.knowm.xchange.bitmex.BitmexAdapters.adaptTrades(BitmexAdapters.java:84) 
 ! at org.knowm.xchange.bitmex.service.BitmexMarketDataService.getTrades(BitmexMarketDataService.java:97) 
 ! at com.gruelbox.orko.marketdata.MarketDataSubscriptionManager$Poller.pollAndEmitTrades(MarketDataSubscriptionManager.java:901) 
```

**To Reproduce**
Add a bitmex coin to subscriptions and wait

**Comment by badgerwithagun** [comment]
Looks like this was fixed by an XChange pull.
