### ISSUE TITLE
Wrong trailing stop on binance calculation 

### ISSUE THREAD

**Issue by konqueror1** [gruelbox/orko#810]
**Describe the bug**
I am adding a trailing stop buy order for LTC/USDT with initial stop 37.1 and limit price 37. Current price is ~37.5. When submit the stop executes immediately with this in the log:

Trailing stop on binance LTC/USDT market hit stop price (37.57000000 < 37.10)
It is obvious that 37.57 is not less than 37.10.

Tested with the latest official release 0.15.2 and with bleeding-edge snapshot 0.15.3-SNAPSHOT

**Expected behavior**
I expect the order execution to happen when current price >= 37.1

**Comment by badgerwithagun** [comment]
I think it's just the message that's wrong.  The code does this:
```
if
 job.direction = SELL and ticker.bidPrice <= stopPrice
or
 job.direction = BUY and ticker.askPrice >= stopPrice
```
But it always uses the same message.

[Code here](https://github.com/gruelbox/orko/blob/6026b472447194c0246b80069a110795618651bc/orko-common/src/main/java/com/gruelbox/orko/job/SoftTrailingStopProcessor.java#L179).

It's a very simple fix.

**Comment by AwooOOoo** [comment]
Hi Graham,
    I new to the Circleci pipeline and saw it reported that the build failed. It compiled locally with Maven, could you give me some pointers as to what I missed?

Paul

**Comment by AwooOOoo** [comment]
Ok Fixed that...Stale POM snapshots 0.15.2 vs. 0.15.3. Now it compiles, but integration testing fails. When I run the integration tests locally, I get the following error repeated:

ERROR [2020-08-14 19:01:10,535] com.gruelbox.orko.auth.ipwhitelisting.IpWhitelistingService: Access attempt from [127.0.0.1] not whitelisted

How do I add IP whitelisting to get the tests to run?

**Comment by badgerwithagun** [comment]
Hey @AwooOOoo.  Check out the file `start-integration-test.sh` which shows how to run the app with the integration test specific configuration. In the IDE you just need to run the main class with `server ../integration-test-config.yml` (or something like that) in the IDE's run configuration.

**Comment by AwooOOoo** [comment]
@badgerwithagun, I was running start-integration-test.sh (command line) when I get the above-listed error repeatedly.

**Comment by badgerwithagun** [comment]
Try `mvn -Pe2etest verify`.

That starts up an instance of the app and runs the tests in the same way as on CircleCI, which we know works.

Does that work for you?

**Comment by AwooOOoo** [comment]
It runs, but now I am seeing a failure in Orko Job tests... (good times)

<pre>[<font color="#CC0000"><b>ERROR</b></font>] <font color="#CC0000"><b>Failures: </b></font>
[<font color="#CC0000"><b>ERROR</b></font>] <font color="#CC0000"><b>  TestJobExecution.testFailOnStopNonResident:235 </b></font>
<font color="#CC0000"><b>Wanted but not invoked:</b></font>
<font color="#CC0000"><b>statusUpdateService.status(&quot;JOB1&quot;, SUCCESS);</b></font>
<font color="#CC0000"><b>-&gt; at com.gruelbox.orko.jobrun.TestJobExecution.testFailOnStopNonResident(TestJobExecution.java:235)</b></font>
<font color="#CC0000"><b>Actually, there were zero interactions with this mock.</b></font>

[<font color="#3465A4"><b>INFO</b></font>] 
[<font color="#CC0000"><b>ERROR</b></font>] <font color="#CC0000"><b>Tests run: 30, Failures: 1, Errors: 0, Skipped: 0</b></font>
[<font color="#3465A4"><b>INFO</b></font>] 
[<font color="#3465A4"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#3465A4"><b>INFO</b></font>] <b>Reactor Summary for Orko 0.15.3-SNAPSHOT:</b>
[<font color="#3465A4"><b>INFO</b></font>] 
[<font color="#3465A4"><b>INFO</b></font>] Orko ............................................... <font color="#4E9A06"><b>SUCCESS</b></font> [  0.023 s]
[<font color="#3465A4"><b>INFO</b></font>] Orko Base .......................................... <font color="#4E9A06"><b>SUCCESS</b></font> [ 15.519 s]
[<font color="#3465A4"><b>INFO</b></font>] Orko DB Testsupport ................................ <font color="#4E9A06"><b>SUCCESS</b></font> [  0.771 s]
[<font color="#3465A4"><b>INFO</b></font>] Orko Auth .......................................... <font color="#4E9A06"><b>SUCCESS</b></font> [ 33.167 s]
[<font color="#3465A4"><b>INFO</b></font>] Orko Job ........................................... <font color="#CC0000"><b>FAILURE</b></font> [01:22 min]
[<font color="#3465A4"><b>INFO</b></font>] Orko Common ........................................ <font color="#C4A000"><b>SKIPPED</b></font>
[<font color="#3465A4"><b>INFO</b></font>] Orko Monolith Application .......................... <font color="#C4A000"><b>SKIPPED</b></font>
[<font color="#3465A4"><b>INFO</b></font>] Orko End-to-End Tests .............................. <font color="#C4A000"><b>SKIPPED</b></font>
[<font color="#3465A4"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#3465A4"><b>INFO</b></font>] <font color="#CC0000"><b>BUILD FAILURE</b></font>
[<font color="#3465A4"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#3465A4"><b>INFO</b></font>] Total time:  02:12 min
[<font color="#3465A4"><b>INFO</b></font>] Finished at: 2020-08-15T12:46:22+02:00
[<font color="#3465A4"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#CC0000"><b>ERROR</b></font>] Failed to execute goal <font color="#4E9A06">org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test</font> <b>(default-test)</b> on project <font color="#06989A">orko-job</font>: <font color="#CC0000"><b>There are test failures.</b></font>
[<font color="#CC0000"><b>ERROR</b></font>] 
[<font color="#CC0000"><b>ERROR</b></font>] <font color="#CC0000"><b>Please refer to /home/paul/Code/tmp/orko/orko-job/target/surefire-reports for the individual test results.</b></font>
[<font color="#CC0000"><b>ERROR</b></font>] <font color="#CC0000"><b>Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.</b></font>
[<font color="#CC0000"><b>ERROR</b></font>] -&gt; <b>[Help 1]</b>
[<font color="#CC0000"><b>ERROR</b></font>] 
[<font color="#CC0000"><b>ERROR</b></font>] To see the full stack trace of the errors, re-run Maven with the <b>-e</b> switch.
[<font color="#CC0000"><b>ERROR</b></font>] Re-run Maven using the <b>-X</b> switch to enable full debug logging.
[<font color="#CC0000"><b>ERROR</b></font>] 
[<font color="#CC0000"><b>ERROR</b></font>] For more information about the errors and possible solutions, please read the following articles:
[<font color="#CC0000"><b>ERROR</b></font>] <b>[Help 1]</b> http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[<font color="#CC0000"><b>ERROR</b></font>] 
[<font color="#CC0000"><b>ERROR</b></font>] After correcting the problems, you can resume the build with the command
[<font color="#CC0000"><b>ERROR</b></font>]   <b>mvn &lt;args&gt; -rf :orko-job</b>
</pre>

**Comment by badgerwithagun** [comment]
Exactly the same as here:

https://circleci.com/workflow-run/62b4f5fc-8447-4ed6-9e01-c672cffb59c0

So it's not you! Looks like something changed between the old 5.0.0 version of XChange it last successfully built against and 5.0.0. fun times as you say...

**Comment by AwooOOoo** [comment]
It looks like the following test cases are the ones with issues:

**Orko Job:** testFailOnStopNonResident() - **1 Error** _(TestJobExecution.testFailOnStopNonResident:235 
Wanted but not invoked:
statusUpdateService.status("JOB1", SUCCESS);
-> at com.gruelbox.orko.jobrun.TestJobExecution.testFailOnStopNonResident(TestJobExecution.java:235)
Actually, there were zero interactions with this mock.)_

**Orko Common:** testSubscriptionsDirect() - **2 Errors** _(Timed out waiting for SubscriptionControllerImpl)_
**Orko Common:** TestEventBusSubscriptionDifferentSubscriberInner() - **2 Errors** _(Timed out waiting for SubscriptionControllerImpl)_
**Orko Common:** testEventBusSubscriptionSameSubscriber() - **2 Errors** _(Timed out waiting for SubscriptionControllerImpl)_
**Orko Common:** testEventBusSubscriptionDifferentSubscriberOuter() - **1 Error** _(Timed out waiting for SubscriptionControllerImpl)_
